development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: louis
  password: pass
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: louis
  password: pass
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: louis
  password: pass